import { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    home: 'Home',
    about: 'About',
    topics: 'Topics',
    abstract: 'Abstract',
    registration: 'Registration Fees',
    contact: 'Contact',
    venue: 'Venue',
    registerNow: 'Register Now',
    submitAbstract: 'Submit Abstract',
    hero_title: 'ACI-SD 2027',
    hero_subtitle: '1st International Conference on Advancing Chemistry and Innovation Towards the Future: Nanotechnology, Artificial Intelligence, and Entrepreneurship for Sustainable Development (ACI-SD 2027)',
    hero_subtitle2: '11th International Symposium of the Mediterranean Group of Pesticide Research',
    hero_date: '27-30 January 2027',
    hero_location: 'Sharm El-Sheikh, EGYPT',
    about_title: 'About the Conference',
    about_invite_title: 'Invitation',
    about_invite:
      'Dear Colleagues, Researchers, Academicians, Industry Experts, and Students,\nOn behalf of the Organizing Committee, we are delighted to invite you to the 1st International Conference on Advancing Chemistry and Innovation Towards the Future: Nanotechnology, Artificial Intelligence, and Entrepreneurship for Sustainable Development (ACI-SD 2027), jointly organized with the 11th International Symposium of the Mediterranean Group of Pesticide Research, to be held in Sharm El-Sheikh, Egypt, from 27\u201330 January 2027. The conference, organized by the Scientific Society of Chemistry (SSC) and Borg Al Arab Technological University, in collaboration with national and international partners, will provide a distinguished international platform for presenting cutting-edge research, exchanging knowledge, and promoting interdisciplinary collaboration in chemistry, nanotechnology, artificial intelligence, sustainable industry, environmental technologies, energy, agriculture, and innovation. The scientific program will feature keynote and invited lectures, oral and poster presentations, panel discussions, industrial exhibitions, and networking activities that strengthen collaboration between academia, industry, and government while advancing sustainable development and technology transfer. The 11th International Symposium of the Mediterranean Group of Pesticide Research will continue its tradition of promoting scientific excellence in pesticide research, environmental safety, plant protection, and sustainable agriculture, bringing together leading scientists and early-career researchers from around the world. Set in the world-renowned resort city of Sharm El-Sheikh, the conference offers an exceptional environment for scientific exchange, international networking, and the development of collaborative partnerships. We warmly invite researchers, academics, professionals, industry representatives, and students to join us and contribute to the success of this prestigious international event. We look forward to welcoming you to Sharm El-Sheikh, Egypt, in January 2027.',
    about_host_title: 'Host Organizations',
    about_ssc:
      'The Scientific Society of Chemistry (SSC) is an independent scientific organization dedicated to advancing chemical sciences through research excellence, innovation, entrepreneurship, and technology transfer. As a multidisciplinary platform, SSC promotes scientific collaboration among academia, industry, research institutions, policymakers, and young scientists by organizing international conferences, workshops, training programs, and collaborative research initiatives. The Society supports interdisciplinary research integrating chemistry with nanotechnology, artificial intelligence, advanced materials, biotechnology, and environmental technologies to address global challenges in health, energy, water, agriculture, and sustainable industrial development while fostering international cooperation and innovation-driven solutions.',
    about_batu:
      'Borg Al Arab Technological University (BATU) is one of Egypt\u2019s leading technological universities, committed to applied education, innovation, and industry-oriented research in alignment with Egypt\u2019s Vision 2030 and the Sustainable Development Goals (SDGs). Through multidisciplinary education, applied research, and strong partnerships with industry and international institutions, BATU promotes technological innovation, entrepreneurship, knowledge transfer, and sustainable industrial development, while preparing highly skilled graduates and contributing to regional and global scientific and technological advancement.',
    about_theme_title: 'Conference Theme',
    about_theme:
      'The conference theme, \u201cAdvancing Chemistry, Applied Technology, Artificial Intelligence, and Innovation for a Sustainable Future,\u201d highlights the integration of scientific research, technological innovation, and entrepreneurship to address global challenges in energy, environment, water, agriculture, health, and sustainable industry. ACI-SD 2027 provides a multidisciplinary platform that promotes interdisciplinary collaboration, knowledge exchange, and the development of innovative solutions supporting sustainable development and industrial transformation.',
    about_obj_title: 'Objectives',
    about_obj_lead: 'After participating in the conference, attendees will be able to:',
    about_objective_1:
      'Discuss emerging advances in chemistry, nanotechnology, AI, sustainable industry, and environmental technologies.',
    about_objective_2:
      'Identify research challenges and innovative solutions in materials science, energy, water, agriculture, and industrial applications.',
    about_objective_3:
      'Exchange knowledge, foster interdisciplinary collaboration, and strengthen international partnerships.',
    about_objective_4:
      'Explore AI-driven technologies, technology transfer, entrepreneurship, and innovation for sustainable development.',
    about_objective_5:
      'Promote scientific research and innovation, with particular support for early-career researchers and students.',
    stat_international: 'International Conference',
    stat_topics: '8 Research Topics',
    stat_speakers: '50+ Speakers',
    stat_location: 'Sharm El-Sheikh, Egypt',
    topics_title: 'Conference Topics',
    topic_chemistry: 'Advanced Chemistry, Functional Materials for Industrial Applications',
    topic_chemistry_desc: 'Cutting-edge research in chemical synthesis, smart polymers, MOFs, and advanced materials for industrial applications',
    topic_nano: 'Nanotechnology & Nanoscale Science',
    topic_nano_desc: 'Innovations in nanoscale science, nano-enabled devices, and industrial nanotech applications',
    topic_energy: 'Energy, Sustainability & Clean Technologies',
    topic_energy_desc: 'Renewable energy systems, storage solutions, hydrogen technologies, and sustainable energy practices',
    topic_agro: 'Agrochemical Sciences, Smart Agriculture & Environmental Safety',
    topic_agro_desc: 'Sustainable agriculture, smart farming, pesticide research, environmental safety, and agro-biotechnology',
    topic_ai: 'Artificial Intelligence, Data Science & Digital Transformation for Chemical, Industrial and Agricultural Systems',
    topic_ai_desc: 'AI methods, machine learning, data science, digital twins, and intelligent decision-support systems applied to chemical, industrial, environmental, energy, and agricultural applications.',
    topic_enviro: 'Environmental Technologies, Water & Circular Economy',
    topic_enviro_desc: 'Clean technologies for water treatment, pollution control, resource recovery, and circular economy',
    topic_engineering: 'Chemical & Process Engineering for Sustainable Industry',
    topic_engineering_desc: 'Advanced process design, intensification, separation technologies, and sustainable industrial engineering',
    topic_innovation: 'Innovation, Entrepreneurship & Technology Transfer',
    topic_innovation_desc: 'Translating research into commercial applications, startups, and industry-academia partnerships',
    committee: 'Committees',
    committee_title: 'Conference Committees',
    executiveCommitteeNav: 'Executive Committee',
    organizingCommitteeNav: 'Organizing Committee',
    scientificCommitteeNav: 'Scientific Committee',
    abstract_title: 'Call for Abstracts',
    abstract_email: 'Submit to: sci.s.o.chemistry@gmail.com',
    abstract_words: '200-300 words',
    abstract_format: '12-point Font size, Times New Roman, Bold, A4',
    abstract_deadline: 'Deadline: 30 November 2026',
    abstract_oral: 'Oral Presentation Template',
    abstract_oral_subtitle: 'Presentation Time: 15\u201320 Minutes',
    abstract_poster: 'Poster Presentation Template',
    abstract_poster_subtitle: 'Poster Size: 90 \u00d7 120 cm',
    abstract_template: 'Abstract Template',
    abstract_template_subtitle: 'Download the official conference abstract template.',
    downloadTemplate: 'Download Abstract Template',
    dates_title: 'Important Dates',
    date_submission: 'Abstract Submission',
    date_acceptance: 'Notification of Acceptance',
    date_final_paper: 'Final Paper Submission',
    date_registration: 'Registration Deadline',
    registration_title: 'Registration',
    reg_intro: 'Welcome to the Conference. Please find below the registration fees and related information.',
    reg_fee_schedule: 'Registration Fee Schedule',
    reg_header_category: 'Category',
    reg_header_double: 'Double Occupancy',
    reg_header_single: 'Single Occupancy',
    reg_header_egp_onsite: 'Egyptian (EGP) Onsite',
    reg_header_egp_online: 'Egyptian (EGP) Online',
    reg_header_eur_onsite: 'International (Euro) Onsite',
    reg_header_eur_online: 'International (Euro) Online',
    reg_category_full_paper: 'Full Paper Presentation',
    reg_category_abstract: 'Abstract Only Presentation',
    reg_category_attendee: 'Attendee (non-presenter)',
    reg_category_accompanying: 'Accompanying Person',
    reg_not_available: '\u2014',
    reg_student_title: 'Student Discount',
    reg_student_text: 'Full-time undergraduate and postgraduate students are eligible for a 15% discount on the applicable registration fee upon submission of a valid student identification card.',
    bank_details: 'Bank Transfer Details',
    bank_account: 'Account Name: Scientific Society of Chemistry (SSC)',
    bank_name: 'Bank Name: Egyptian Arab Land Bank (EALB)',
    reg_account_number: 'Account Number:',
    reg_iban: 'IBAN:',
    reg_swift: 'SWIFT Code:',
    reg_copied: 'Copied!',
    reg_includes_title: 'Registration Includes',
    reg_include_publication: 'Coverage of the publication fee for accepted papers in the conference Special Issue of Emergent Materials (Q1, Scopus), published by Springer Nature',
    reg_include_accommodation: 'Three-night accommodation (four days) on a Soft All-Inclusive basis at the conference hotel.',
    reg_include_sessions: 'Access to All Sessions and Digital Conference Proceedings',
    reg_include_program: 'Printed Conference Program',
    reg_include_gift_bag: 'Conference Gift Bag and Certificate of Presentation',
    reg_not_includes_title: 'The registration fee does not include:',
    reg_not_include_visa_transport: 'Visa application fee, Airfare and transportation expenses',
    reg_not_include_one_author: 'Each registration covers one participant only.',
    reg_not_include_additional_authors: 'Co-authors wishing to attend the conference are required to register separately.',
    reg_additional_title: 'Additional Information',
    reg_additional_video: 'Virtual presentations are available for participants who are unable to attend in person.',
    reg_additional_early: 'Early registration is strongly encouraged.',
    reg_cancellation_title: 'Cancellation & Refund Policy',
    reg_cancellation_intro: 'Cancellation requests must be submitted by email.',
    reg_cancellation_1: 'By 31 October 2026: 80% refund',
    reg_cancellation_2: '1\u201330 November 2026: 50% refund',
    reg_cancellation_3: 'From 1 December 2026: No refund',
    reg_cancellation_note: 'Refunds will be processed within 30 working days after the conference. Bank charges are the participant\u2019s responsibility. Registration transfers to another participant from the same institution are permitted until 15 January 2027, subject to Organizing Committee approval.',
    venue_title: 'Venue',
    venue_location: 'Hotel on the Corniche, Sharm El-Sheikh, Egypt',
    venue_region: 'Red Sea Coast',
    venue_intro:
      'Rehana Sharm Resort provides a modern and comfortable setting for the symposium, featuring professional conference facilities, quality accommodation, and a prime location near the Red Sea. The venue offers an ideal environment for scientific exchange, networking, and international collaboration.',
    venue_accommodation_title: 'Accommodation',
    venue_accommodation_desc: 'Conference venue hotel near the beach and Sharm El-Sheikh corniche.',
    venue_tour: 'Professional Networking Experience',
    venue_tour_desc: 'A welcoming environment designed for scientific exchange, collaboration, and engagement.',
    venue_language: 'Conference Language: English',
    venue_language_desc: 'All scientific sessions, presentations, and official communications will be conducted in English.',
    organized_by: 'Organized by',
    hero_discount_text: 'Accepted papers, subject to peer review and editorial acceptance, will be published in the conference Special Issue of Emergent Materials (Q1, Scopus), Springer Nature (ISSN: 2522-5731; E-ISSN: 2522-574X).',
    hero_discount_url: 'https://link.springer.com/journal/42247',
    footer_desc: 'Advancing Chemistry and Innovation Towards Sustainable Development',
    footer_links: 'Quick Links',
    footer_contact: 'Contact Information',
    back_to_top: 'Back to top',
    copyright: '© 2027 ACI-SD | Scientific Society of Chemistry'
  },
  ar: {
    home: 'الرئيسية',
    about: 'عن المؤتمر',
    topics: 'المحاور',
    abstract: 'الملخصات',
    registration: 'التسجيل',
    contact: 'اتصل بنا',
    venue: 'مكان الانعقاد',
    registerNow: 'سجل الآن',
    submitAbstract: 'قدم ملخص',
    hero_title: 'ACI-SD 2027',
    hero_subtitle: 'المؤتمر الدولي الأول للنهوض بالكيمياء والابتكار من أجل التنمية المستدامة',
    hero_subtitle2: 'الندوة الحادية عشرة لمجموعة البحر المتوسط لأبحاث المبيدات',
    hero_date: '27-30 يناير 2027',
    hero_location: 'شرم الشيخ، مصر',
    about_title: 'عن المؤتمر',
    about_invite_title: 'الدعوة',
    about_invite:
      'زملائي الأعزاء، الباحثون، الأكاديميون، خبراء الصناعة، والطلاب،\n\nيسعدنا الإعلان عن انعقاد المؤتمر الدولي الأول للنهوض بالكيمياء والابتكار نحو المستقبل: تكنولوجيا النانو والذكاء الاصطناعي وريادة الأعمال من أجل التنمية المستدامة (ACI-SD 2027)، والذي يُعقد بالتزامن مع الندوة الحادية عشرة لمجموعة البحر المتوسط لأبحاث المبيدات، في شرم الشيخ، مصر، خلال الفترة من 27 إلى 30 يناير 2027. ينظم المؤتمر الجمعية العلمية للكيمياء (SSC) وجامعة برج العرب التكنولوجية بالتعاون مع مؤسسات أكاديمية وبحثية دولية ومحلية مرموقة، ليجمع العلماء والباحثين والمبتكرين وقادة الصناعة وصناع السياسات والطلاب من جميع أنحاء العالم. يهدف ACI-SD 2027 إلى توفير منصة دولية ديناميكية لتبادل المعرفة العلمية وعرض الأبحاث المتطورة وتعزيز التعاون متعدد التخصصات في مجالات الكيمياء وتكنولوجيا النانو والذكاء الاصطناعي والصناعة المستدامة والتقنيات البيئية والطاقة والزراعة وريادة الأعمال والابتكار. يسعى المؤتمر إلى تعزيز الصلة بين البحث العلمي والتطبيقات الصناعية وأهداف التنمية المستدامة من خلال الحوار البناء وتبادل المعرفة. سيتضمن البرنامج العلمي محاضرات رئيسية وندوات مدعوة وعروضًا شفوية وملصقات وجلسات نقاشية ومعارض صناعية وفرص للتواصل تهدف إلى تشجيع التعاون بين الأوساط الأكاديمية والصناعية والحكومية. وسيتم التركيز بشكل خاص على التقنيات الناشئة والمواد المتقدمة والتصنيع الذكي والابتكار القائم على الذكاء الاصطناعي والزراعة المستدامة وحماية البيئة وتقنيات المياه والطاقة المتجددة ونقل التكنولوجيا.\n\nبالتوازي، ستواصل الندوة الحادية عشرة لمجموعة البحر المتوسط لأبحاث المبيدات تقليدها العريق في تعزيز التميز العلمي والتعاون الدولي في أبحاث المبيدات والسلامة البيئية وحماية النباتات والزراعة المستدامة والمجالات ذات الصلة. ستجمع الندوة نخبة من الخبراء والباحثين الشباب لمناقشة أحدث التطورات والتحديات والآفاق المستقبلية في هذه المجالات المهمة. يوفر مكان انعقاد المؤتمر في مدينة شرم الشيخ الجميلة بيئة ملهمة للتبادل العلمي والتواصل الدولي. ستتاح للمشاركين فرصة التفاعل مع خبراء مرموقين وبناء تعاونات جديدة والمساهمة في صياغة حلول مبتكرة للتحديات العلمية والمجتمعية العالمية. ندعو الباحثين والأكاديميين والمهنيين والشركاء الصناعيين وطلاب الدراسات العليا وممثلي المنظمات الحكومية وغير الحكومية للمشاركة في هذا الحدث الدولي المتميز والمساهمة في نجاحه العلمي. نتطلع إلى الترحيب بكم في شرم الشيخ، مصر، في تجمع ملهم ومثمر للمجتمع العلمي الدولي.',
    about_host_title: 'الجهة المنظمة',
    about_ssc:
      'الجمعية العلمية للكيمياء (SSC) هي منظمة علمية مستقلة تهدف إلى النهوض بالعلوم الكيميائية وتعزيز التميز البحثي ودعم الابتكار من أجل التنمية المستدامة. تعمل الجمعية كمنصة متعددة التخصصات تجمع الباحثين والأكاديميين وخبراء الصناعة وصناع السياسات والعلماء الشباب لتسهيل التعاون العلمي وتبادل المعرفة وبناء القدرات على المستويين الوطني والدولي. تلتزم SSC بدعم البحث العلمي والابتكار وريادة الأعمال ونقل التكنولوجيا من خلال تنظيم المؤتمرات الدولية وورش العمل العلمية والبرامج التدريبية والمبادرات البحثية التعاونية. تعزز الجمعية بنشاط المناهج متعددة التخصصات التي تدمج الكيمياء مع المجالات الناشئة مثل تكنولوجيا النانو والذكاء الاصطناعي والمواد المتقدمة والتقنيات البيئية والتكنولوجيا الحيوية والتنمية الصناعية المستدامة. من خلال شبكتها الواسعة من المؤسسات الأكاديمية ومراكز البحوث والشركاء الصناعيين والخبراء الدوليين، تساهم SSC في تعزيز التعاون العلمي وتقديم حلول مؤثرة للتحديات العالمية المتعلقة بالصحة والطاقة والمياه والبيئة والزراعة والتقنيات المستدامة. تكرس الجمعية جهودها لتمكين الجيل القادم من العلماء والمبتكرين مع دعم ترجمة الاكتشافات العلمية إلى تطبيقات عملية تفيد المجتمع والصناعة. بصفتها منظمة المؤتمر الدولي للنهوض بالكيمياء والتكنولوجيا التطبيقية والابتكار نحو المستقبل (ACI-SD 2027)، تؤكد SSC التزامها بتعزيز التميز العلمي والتعاون الدولي والتنمية المستدامة القائمة على الابتكار.',
    about_batu:
      'جامعة برج العرب التكنولوجية (BATU) هي إحدى الجامعات التكنولوجية الرائدة في مصر، أُنشئت للنهوض بالتعليم التطبيقي والابتكار والبحث الموجه نحو الصناعة بما يتماشى مع رؤية مصر 2030 وأهداف التنمية المستدامة. تقع الجامعة في موقع استراتيجي بمدينة برج العرب—إحدى أكبر المناطق الصناعية والاقتصادية في مصر والشرق الأوسط—لتكون مركزًا ديناميكيًا يربط الأوساط الأكاديمية والبحث والتكنولوجيا والصناعة. تلتزم BATU بتطوير خريجين ذوي مهارات عالية وتعزيز التميز العلمي من خلال التعليم متعدد التخصصات والبحث التطبيقي والابتكار التكنولوجي وريادة الأعمال والتنمية الصناعية المستدامة. تعزز الجامعة شراكات قوية مع القطاعات الصناعية والمؤسسات البحثية والمنظمات الدولية لتسريع نقل المعرفة ودعم الانتقال نحو اقتصاد قائم على المعرفة والابتكار. من خلال التزامها بالجودة الأكاديمية والتقدم التكنولوجي والتعاون الدولي، تلعب BATU دورًا نشطًا في مواجهة التحديات المعاصرة في العلوم والتكنولوجيا والاستدامة والتحول الصناعي، مع المساهمة في مبادرات التنمية الإقليمية والعالمية.',
    about_theme_title: 'محور المؤتمر',
    about_theme:
      'تشرفت اللجنة المنظمة للمؤتمر الدولي للنهوض بالكيمياء والتكنولوجيا التطبيقية والابتكار نحو المستقبل: تكنولوجيا النانو والذكاء الاصطناعي وريادة الأعمال والصناعة المستدامة (ACI-SD 2027)، والذي يُعقد بالتزامن مع الندوة الحادية عشرة لمجموعة البحر المتوسط لأبحاث المبيدات، بدعوة الباحثين والأكاديميين وقادة الصناعة والمبتكرين ورواد الأعمال والطلاب من جميع أنحاء العالم للمشاركة في هذا الحدث الدولي المتميز، والذي سيقام في شرم الشيخ، مصر، خلال الفترة من 27 إلى 30 يناير 2027. يهدف ACI-SD 2027 إلى معالجة التحديات العلمية والتكنولوجية الأكثر إلحاحًا والناشئة التي تشكل مستقبل التنمية المستدامة. سيوفر المؤتمر منصة متعددة التخصصات لعرض الأبحاث المتطورة وتبادل الأفكار المبتكرة وتعزيز التعاون بين الأوساط الأكاديمية والصناعية والمؤسسات البحثية وصناع السياسات. يعكس محور المؤتمر "النهوض بالكيمياء والتكنولوجيا التطبيقية والذكاء الاصطناعي والابتكار من أجل مستقبل مستدام" الحاجة المتزايدة لدمج الاكتشاف العلمي والتقدم التكنولوجي وريادة الأعمال والابتكار الصناعي لمواجهة التحديات العالمية المتعلقة بالطاقة والبيئة والمياه والزراعة والصحة والنمو الاقتصادي المستدام. من خلال المحاضرات الرئيسية والعروض العلمية وحلقات النقاش وفرص التواصل، يسعى المؤتمر إلى تعزيز التعاون الدولي وتسريع ترجمة المعرفة العلمية إلى حلول عملية.',
    about_obj_title: 'الأهداف',
    about_obj_lead: 'بعد المشاركة في هذا المؤتمر، يجب أن يكون المشاركون قادرين على:',
    about_objective_1:
      'مناقشة الاتجاهات الحالية والناشئة في الكيمياء وتكنولوجيا النانو والذكاء الاصطناعي والصناعة المستدامة والتقنيات البيئية.',
    about_objective_2:
      'تحديد التحديات والفرص البحثية الرئيسية في المواد المتقدمة والطاقة والمياه والزراعة والابتكار الصناعي.',
    about_objective_3:
      'تبادل المعرفة العلمية وأفضل الممارسات بين الباحثين والمهنيين الصناعيين ورواد الأعمال وصناع السياسات.',
    about_objective_4:
      'استكشاف دور الذكاء الاصطناعي والتحول الرقمي في تسريع الاكتشاف العلمي والتنمية الصناعية.',
    about_objective_5:
      'تعزيز التعاون متعدد التخصصات والشراكات الدولية لمواجهة تحديات الاستدامة العالمية.',
    about_objective_6:
      'تسليط الضوء على التطورات الحديثة في أبحاث المبيدات والزراعة المستدامة والسلامة البيئية والابتكار الكيميائي الزراعي.',
    about_objective_7:
      'تعزيز نقل التكنولوجيا وريادة الأعمال والحلول القائمة على الابتكار التي تدعم التنمية الاقتصادية والمجتمعية المستدامة.',
    about_objective_8:
      'تشجيع الباحثين الشباب والطلاب على الانخراط في البحث العلمي والابتكار والتعاون الدولي.',
    stat_international: 'مؤتمر دولي',
    stat_topics: '8 محاور بحثية',
    stat_speakers: '+50 متحدث',
    stat_location: 'شرم الشيخ، مصر',
    topics_title: 'محاور المؤتمر',
    topic_chemistry: 'الكيمياء المتقدمة والمواد الوظيفية للتطبيقات الصناعية',
    topic_chemistry_desc: 'أبحاث متطورة في التركيب الكيميائي والبوليمرات الذكية والأطر الفلزية العضوية والمواد المتقدمة للتطبيقات الصناعية',
    topic_nano: 'تكنولوجيا النانو وعلوم المقياس النانوي',
    topic_nano_desc: 'ابتكارات في علوم النانو والأجهزة المعززة بالنانو وتطبيقاته الصناعية',
    topic_energy: 'الطاقة والاستدامة والتقنيات النظيفة',
    topic_energy_desc: 'أنظمة الطاقة المتجددة وحلول التخزين وتقنيات الهيدروجين وممارسات الطاقة المستدامة',
    topic_agro: 'علوم الكيمياء الزراعية والزراعة الذكية والسلامة البيئية',
    topic_agro_desc: 'الزراعة المستدامة والزراعة الذكية وأبحاث المبيدات والسلامة البيئية والتكنولوجيا الحيوية الزراعية',
    topic_ai: 'الذكاء الاصطناعي وعلوم البيانات والأنظمة الكيميائية الذكية',
    topic_ai_desc: 'التعلم الآلي وتحليل البيانات والاكتشاف المدعوم بالذكاء الاصطناعي وأنظمة التصنيع الكيميائي الذكية',
    topic_enviro: 'التقنيات البيئية والمياه والاقتصاد الدائري',
    topic_enviro_desc: 'التقنيات النظيفة لمعالجة المياه ومكافحة التلوث واسترداد الموارد والاقتصاد الدائري',
    topic_engineering: 'الهندسة الكيميائية وهندسة العمليات من أجل الصناعة المستدامة',
    topic_engineering_desc: 'تصميم العمليات المتقدمة وتكثيفها وتقنيات الفصل والهندسة الصناعية المستدامة',
    topic_innovation: 'الابتكار وريادة الأعمال ونقل التكنولوجيا',
    topic_innovation_desc: 'تحويل البحث إلى تطبيقات تجارية والشركات الناشئة والشراكات بين الصناعة والأوساط الأكاديمية',
    committee: 'اللجان',
    committee_title: 'لجان المؤتمر',
    executiveCommitteeNav: 'اللجنة التنفيذية',
    organizingCommitteeNav: 'اللجنة التنظيمية',
    scientificCommitteeNav: 'اللجنة العلمية',
    abstract_title: 'الدعوة لتقديم الملخصات',
    abstract_email: 'أرسل إلى: sci.s.o.chemistry@gmail.com',
    abstract_words: '200-300 كلمة',
    abstract_format: '12-pt حجم الخط, Times New Roman، عريض، A4',
    abstract_deadline: 'الموعد النهائي: 30 نوفمبر 2026',
    abstract_oral: 'قالب العرض الشفهي',
    abstract_oral_subtitle: 'مدة التقديم: 15\u201320 دقيقة',
    abstract_poster: 'قالب عرض الملصق',
    abstract_poster_subtitle: 'حجم الملصق: 90 \u00d7 120 سم',
    abstract_template: 'قالب الملخص',
    abstract_template_subtitle: 'تحميل قالب الملخص الرسمي للمؤتمر.',
    downloadTemplate: 'تحميل قالب الملخص',
    dates_title: 'التواريخ المهمة',
    date_submission: 'تقديم الملخص',
    date_acceptance: 'الإخطار بالقبول',
    date_final_paper: 'تقديم الورقة النهائية',
    date_registration: 'الموعد النهائي للتسجيل',
    registration_title: 'التسجيل',
    reg_intro: 'مرحبًا بكم في المؤتمر. يرجى الاطلاع أدناه على رسوم التسجيل والمعلومات ذات الصلة.',
    reg_fee_schedule: 'جدول رسوم التسجيل',
    reg_header_category: 'الفئة',
    reg_header_double: 'غرفة مزدوجة',
    reg_header_single: 'غرفة مفردة',
    reg_header_egp_onsite: 'مصري (جنيه) حضور شخصي',
    reg_header_egp_online: 'مصري (جنيه) عبر الإنترنت',
    reg_header_usd_onsite: 'دولي (دولار) حضور شخصي',
    reg_header_usd_online: 'دولي (دولار) عبر الإنترنت',
    reg_category_full_paper: 'تقديم ورقة كاملة',
    reg_category_abstract: 'تقديم ملخص فقط',
    reg_category_attendee: 'حضور (غير مقدم)',
    reg_category_accompanying: 'مرافق',
    reg_not_available: '\u2014',
    reg_student_title: 'خصم الطلاب',
    reg_student_text: 'يحصل طلاب البكالوريوس والدراسات العليا المتفرغون على خصم 15% على رسوم التسجيل المستحقة عند تقديم بطاقة هوية طلابية سارية المفعول.',
    bank_details: 'تفاصيل التحويل البنكي',
    bank_account: 'الحساب: الجمعية العلمية للكيمياء',
    bank_name: 'البنك: بنك الأراضي المصري العربي',
    reg_account_number: 'رقم الحساب:',
    reg_iban: 'IBAN:',
    reg_swift: 'SWIFT Code:',
    reg_copied: 'تم النسخ!',
    reg_includes_title: 'يشمل التسجيل',
    reg_include_welcome_packet: 'حقيبة ترحيبية للمؤتمر',
    reg_include_publication: 'تغطية رسوم النشر للأوراق المقبولة في العدد الخاص بالمؤتمر من مجلة Emergent Materials (Q1, Scopus) المنشورة من قبل Springer Nature',
    reg_include_sessions: 'الوصول لجميع الجلسات',
    reg_include_proceedings: 'وقائع المؤتمر الرقمية',
    reg_include_program: 'نسخة مطبوعة من دليل البرنامج (للمتحدثين)',
    reg_include_gift_bag: 'حقيبة هدايا من المؤتمر',
    reg_include_certificate: 'شهادة تقديم',
    reg_include_accommodation: 'إقامة لمدة أربعة أيام / ثلاث ليالٍ بنظام الإقامة الشاملة المخففة في فندق المؤتمر.',
    reg_not_includes_title: 'لا يشمل التسجيل',
    reg_not_include_visa: 'رسوم طلب التأشيرة',
    reg_not_include_transport: 'تذاكر الطيران ومصاريف النقل',
    reg_not_include_one_author: 'يغطي التسجيل مشاركًا واحدًا فقط.',
    reg_not_include_additional_authors: 'يجب على المؤلفين المشاركين الراغبين في حضور المؤتمر التسجيل بشكل منفصل.',
    reg_additional_title: 'معلومات إضافية',
    reg_additional_video: 'يتم قبول العروض التقديمية بالفيديو لمن لا يستطيعون الحضور شخصيًا.',
    reg_additional_early: 'نوصي بشدة بالتسجيل المبكر.',
    reg_cancellation_title: 'سياسة الإلغاء واسترداد الرسوم',
    reg_cancellation_intro: 'يجب على المشاركين الراغبين في إلغاء تسجيلهم إخطار أمانة المؤتمر كتابيًا عبر البريد الإلكتروني. سيتم معالجة المبالغ المستردة وفقًا للجدول التالي:',
    reg_cancellation_1: 'الإلغاء في أو قبل 31 أكتوبر 2026: سيتم استرداد 80% من رسوم التسجيل.',
    reg_cancellation_2: 'الإلغاء بين 1 نوفمبر و30 نوفمبر 2026: سيتم استرداد 50% من رسوم التسجيل.',
    reg_cancellation_3: 'الإلغاء في أو بعد 1 ديسمبر 2026: لن يتم إصدار أي استرداد.',
    reg_cancellation_note: 'يرجى العلم أن جميع المبالغ المستردة المعتمدة ستتم معالجتها في غضون 30 يوم عمل بعد انتهاء المؤتمر. أي رسوم تحويل بنكي أو رسوم تحويل عملات أو تكاليف معاملات أخرى تتكبدها أثناء عملية الدفع أو الاسترداد هي مسؤولية المشارك.',
    reg_transfer_title: 'تحويل التسجيل',
    reg_transfer_desc: 'يجوز تحويل التسجيل إلى مشارك آخر من نفس المؤسسة بناءً على طلب كتابي يُقدم إلى أمانة المؤتمر في موعد أقصاه 15 يناير 2027، وذلك بعد موافقة اللجنة المنظمة.',
    venue_title: 'مكان الانعقاد',
    venue_location: 'فندق على الكورنيش، شرم الشيخ، مصر',
    venue_region: 'ساحل البحر الأحمر',
    venue_intro:
      'يوفر منتجع ريهانا شرم الشيخ بيئة حديثة ومريحة للندوة، مع مرافق مؤتمرات احترافية وإقامة عالية الجودة وموقع متميز بالقرب من البحر الأحمر. يقدم المكان بيئة مثالية للتبادل العلمي والتواصل والتعاون الدولي.',
    venue_accommodation_title: 'الإقامة',
    venue_accommodation_desc: 'فندق انعقاد المؤتمر بالقرب من الشاطئ وكورنيش شرم الشيخ.',
    venue_tour: 'بيئة مهنية للتواصل',
    venue_tour_desc: 'أجواء مثالية للتبادل العلمي وبناء الشراكات وتعزيز التفاعل بين المشاركين.',
    venue_language: 'لغة المؤتمر: الإنجليزية',
    venue_language_desc: 'ستُعقد جميع الجلسات العلمية والعروض التقديمية والمراسلات الرسمية باللغة الإنجليزية.',
    organized_by: 'تنظيم',
    hero_discount_text: 'سيتم نشر الأوراق المقبولة، بعد مراجعتها علميًا وقبولها تحريريًا، في العدد الخاص بالمؤتمر من مجلة Emergent Materials (Q1, Scopus)، Springer Nature (ISSN: 2522-5731; E-ISSN: 2522-574X).  https://link.springer.com/journal/42247.',
    hero_discount_url: 'https://link.springer.com/journal/42247',
    footer_desc: 'النهوض بالكيمياء والابتكار نحو التنمية المستدامة',
    footer_links: 'روابط سريعة',
    footer_contact: 'معلومات الاتصال',
    back_to_top: 'العودة إلى الأعلى',
    copyright: '© 2027 ACI-SD | الجمعية العلمية للكيمياء'
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      <div dir={language === 'ar' ? 'rtl' : 'ltr'} className={language === 'ar' ? 'font-cairo' : 'font-inter'}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
