import { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    home: 'Home',
    about: 'About',
    topics: 'Topics',
    abstract: 'Abstract',
    registration: 'Registration Fees',
    contact: 'Contact',
    venue: 'Venue',
    registerNow: 'Register Now',
    submitAbstract: 'Submit Abstract',
    hero_title: 'ACI-SD 2027',
    hero_subtitle: '1st International Conference on Advancing Chemistry and Innovation Towards the Future: Nanotechnology, Artificial Intelligence, and Entrepreneurship for Sustainable Development "ACI-SD 2027"',
    hero_subtitle2: '11th International Symposium of Mediterranean Group on Pesticide Research',
    hero_date: '27-30 January 2027',
    hero_location: 'Sharm El-Sheikh, Egypt',
    about_title: 'About the Conference',
    about_invite_title: 'Invitation',
    about_invite:
      'Dear Colleagues, Researchers, Academicians, Industry Experts, and Students,\n\nWe are pleased to announce the 1st International Conference on Advancing Chemistry and Innovation Towards the Future: Nanotechnology, Artificial Intelligence, and Entrepreneurship for Sustainable Development (ACI-SD 2027), jointly organized with the 11th International Symposium of the Mediterranean Group of Pesticide Research (MGPR), to be held in Sharm El-Sheikh, Egypt, from 27\u201330 January 2027. The conference is organized by the Scientific Society of Chemistry (SSC)and Borg Al Arab Technological University in collaboration with distinguished national and international academic and research institutions, bringing together scientists, researchers, innovators, industrial leaders, policymakers, and students from around the world. ACI-SD 2027 aims to provide a dynamic international platform for exchanging scientific knowledge, presenting cutting-edge research, and fostering interdisciplinary collaboration in the fields of chemistry, nanotechnology, artificial intelligence, sustainable industry, environmental technologies, energy, agriculture, entrepreneurship, and innovation. The conference seeks to strengthen the connection between scientific research, industrial applications, and sustainable development goals through constructive dialogue and knowledge sharing. The scientific program will include keynote lectures, invited talks, oral and poster presentations, panel discussions, industrial exhibitions, and networking opportunities designed to encourage collaboration among academia, industry, and governmental organizations. Special emphasis will be placed on emerging technologies, advanced materials, smart manufacturing, AI-driven innovation, sustainable agriculture, environmental protection, water technologies, renewable energy, and technology transfer.\n\nIn parallel, the 11th International Symposium of Mediterranean Group on Pesticide Research will continue its long-standing tradition of promoting scientific excellence and international cooperation in pesticide research, environmental safety, plant protection, sustainable agriculture, and related disciplines. The symposium will bring together leading experts and young researchers to discuss recent advances, challenges, and future perspectives in these important areas. The conference venue, located in the beautiful city of Sharm El-Sheikh, offers an inspiring environment for scientific exchange and international networking. Participants will have the opportunity to engage with renowned experts, establish new collaborations, and contribute to shaping innovative solutions for global scientific and societal challenges. We cordially invite researchers, academics, professionals, industrial partners, graduate students, and representatives of governmental and non-governmental organizations to participate in this distinguished international event and to contribute to its scientific success. We look forward to welcoming you to Sharm El-Sheikh, Egypt, for an inspiring and productive gathering of the international scientific community.',
    about_host_title: 'Host Organization',
    about_ssc:
      'The Scientific Society of Chemistry (SSC) is an independent scientific organization dedicated to advancing chemical sciences, fostering research excellence, and promoting innovation for sustainable development. The Society serves as a multidisciplinary platform that brings together researchers, academics, industry experts, policymakers, and young scientists to facilitate scientific collaboration, knowledge exchange, and capacity building at both national and international levels. SSC is committed to supporting scientific research, innovation, entrepreneurship, and technology transfer through the organization of international conferences, scientific workshops, training programs, and collaborative research initiatives. The Society actively promotes interdisciplinary approaches that integrate chemistry with emerging fields such as nanotechnology, artificial intelligence, advanced materials, environmental technologies, biotechnology, and sustainable industrial development. Through its extensive network of academic institutions, research centers, industrial partners, and international experts, SSC contributes to strengthening scientific cooperation and fostering impactful solutions to global challenges related to health, energy, water, environment, agriculture, and sustainable technologies. The Society is dedicated to empowering the next generation of scientists and innovators while supporting the translation of scientific discoveries into practical applications that benefit society and industry. As the organizer of the International Conference on Advancing Chemistry, Applied Technology, and Innovation Towards the Future (ACI-SD 2027), SSC reaffirms its mission to promote scientific excellence, international collaboration, and innovation-driven sustainable development.',
    about_batu:
      'Borg Al Arab Technological University (BATU) is one of Egypt\u2019s leading technological universities, established to advance applied education, innovation, and industry-oriented research in alignment with Egypt\u2019s Vision 2030 and the Sustainable Development Goals (SDGs). Strategically located in Borg Al Arab City\u2014one of the largest industrial and economic zones in Egypt and the Middle East\u2014the university serves as a dynamic hub connecting academia, research, technology, and industry. BATU is dedicated to developing highly skilled graduates and fostering scientific excellence through multidisciplinary education, applied research, technological innovation, entrepreneurship, and sustainable industrial development. The university promotes strong partnerships with industrial sectors, research institutions, and international organizations to accelerate knowledge transfer and support the transition toward a knowledge-based and innovation-driven economy. Through its commitment to academic quality, technological advancement, and international collaboration, BATU plays an active role in addressing contemporary challenges in science, technology, sustainability, and industrial transformation, while contributing to regional and global development initiatives.',
    about_theme_title: 'Conference Theme',
    about_theme:
      'The Organizing Committee of the International Conference on Advancing Chemistry, Applied Technology, and Innovation Towards the Future: Nanotechnology, Artificial Intelligence, Entrepreneurship, and Sustainable Industry (ACI-SD 2027), jointly held with the 11th International Symposium of the Mediterranean Group of Pesticide Research , is honored to welcome researchers, academics, industry leaders, innovators, entrepreneurs, and students from around the world to participate in this distinguished international event, which will take place in Sharm El-Sheikh, Egypt, from 27\u201330 January 2027. ACI-SD 2027 aims to address the most pressing and emerging scientific and technological challenges shaping the future of sustainable development. The conference will provide a multidisciplinary platform for presenting cutting-edge research, exchanging innovative ideas, and fostering collaboration among academia, industry, research institutions, and policymakers. The conference theme, \u201cAdvancing Chemistry, Applied Technology, Artificial Intelligence, and Innovation for a Sustainable Future\u201d reflects the growing need to integrate scientific discovery, technological advancement, entrepreneurship, and industrial innovation to address global challenges related to energy, environment, water, agriculture, health, and sustainable economic growth. Through keynote lectures, scientific presentations, panel discussions, and networking opportunities, the conference seeks to strengthen international cooperation and accelerate the translation of scientific knowledge into real-world solutions.',
    about_obj_title: 'Objectives',
    about_obj_lead: 'After participating in this conference, attendees should be able to:',
    about_objective_1:
      'Discuss current and emerging trends in chemistry, nanotechnology, artificial intelligence, sustainable industry, and environmental technologies.',
    about_objective_2:
      'Identify critical research challenges and opportunities in advanced materials, energy, water, agriculture, and industrial innovation.',
    about_objective_3:
      'Exchange scientific knowledge and best practices among researchers, industry professionals, entrepreneurs, and policymakers.',
    about_objective_4:
      'Explore the role of artificial intelligence and digital transformation in accelerating scientific discovery and industrial development.',
    about_objective_5:
      'Promote interdisciplinary collaboration and international partnerships to address global sustainability challenges.',
    about_objective_6:
      'Highlight recent advances in pesticide research, sustainable agriculture, environmental safety, and agrochemical innovation.',
    about_objective_7:
      'Foster technology transfer, entrepreneurship, and innovation-driven solutions that support sustainable economic and societal development.',
    about_objective_8:
      'Encourage young researchers and students to engage in scientific research, innovation, and international collaboration.',
    stat_international: 'International Conference',
    stat_topics: '8 Research Topics',
    stat_speakers: '50+ Speakers',
    stat_location: 'Sharm El-Sheikh, Egypt',
    topics_title: 'Conference Topics',
    topic_chemistry: 'Advanced Chemistry, Functional Materials for Industrial Applications',
    topic_chemistry_desc: 'Cutting-edge research in chemical synthesis, smart polymers, MOFs, and advanced materials for industrial applications',
    topic_nano: 'Nanotechnology & Nanoscale Science',
    topic_nano_desc: 'Innovations in nanoscale science, nano-enabled devices, and industrial nanotech applications',
    topic_energy: 'Energy, Sustainability & Clean Technologies',
    topic_energy_desc: 'Renewable energy systems, storage solutions, hydrogen technologies, and sustainable energy practices',
    topic_agro: 'Agrochemical Sciences, Smart Agriculture & Environmental Safety',
    topic_agro_desc: 'Sustainable agriculture, smart farming, pesticide research, environmental safety, and agro-biotechnology',
    topic_ai: 'AI, Data Science & Smart Chemical Systems',
    topic_ai_desc: 'Machine learning, data analytics, AI-driven discovery, and intelligent chemical manufacturing systems',
    topic_enviro: 'Environmental Technologies, Water & Circular Economy',
    topic_enviro_desc: 'Clean technologies for water treatment, pollution control, resource recovery, and circular economy',
    topic_engineering: 'Chemical & Process Engineering for Sustainable Industry',
    topic_engineering_desc: 'Advanced process design, intensification, separation technologies, and sustainable industrial engineering',
    topic_innovation: 'Innovation, Entrepreneurship & Technology Transfer',
    topic_innovation_desc: 'Translating research into commercial applications, startups, and industry-academia partnerships',
    committee: 'Committees',
    committee_title: 'Conference Committees',
    executiveCommitteeNav: 'Executive Committee',
    organizingCommitteeNav: 'Organizing Committee',
    scientificCommitteeNav: 'Scientific Committee',
    abstract_title: 'Call for Abstracts',
    abstract_email: 'Submit to: sci.s.o.chemistry@gmail.com',
    abstract_words: '200-300 words',
    abstract_format: '12-point Font size, Times New Roman, Bold, A4',
    abstract_deadline: 'Deadline: 30 November 2026',
    abstract_oral: 'Oral Presentation Template',
    abstract_oral_subtitle: 'Presentation Time: 15\u201320 Minutes',
    abstract_poster: 'Poster Presentation Template',
    abstract_poster_subtitle: 'Poster Size: 90 \u00d7 120 cm',
    abstract_template: 'Abstract Template',
    abstract_template_subtitle: 'Download the official conference abstract template.',
    downloadTemplate: 'Download Abstract Template',
    dates_title: 'Important Dates',
    date_submission: 'Abstract Submission',
    date_acceptance: 'Notification of Acceptance',
    date_final_paper: 'Final Paper Submission',
    date_registration: 'Registration Deadline',
    registration_title: 'Registration',
    reg_intro: 'Welcome to the Conference. Please find below the registration fees and related information.',
    reg_fee_schedule: 'Registration Fee Schedule',
    reg_header_category: 'Category',
    reg_header_double: 'Double Occupancy',
    reg_header_single: 'Single Occupancy',
    reg_header_egp_onsite: 'Egyptian (EGP) Onsite',
    reg_header_egp_online: 'Egyptian (EGP) Online',
    reg_header_usd_onsite: 'International (USD) Onsite',
    reg_header_usd_online: 'International (USD) Online',
    reg_category_full_paper: 'Full Paper Presentation',
    reg_category_abstract: 'Abstract Only Presentation',
    reg_category_attendee: 'Attendee (non-presenter)',
    reg_category_accompanying: 'Accompanying Person',
    reg_not_available: '\u2014',
    reg_student_title: 'Student Discount',
    reg_student_text: 'Full-time undergraduate and postgraduate students are eligible for a 15% discount on the applicable registration fee upon submission of a valid student identification card.',
    bank_details: 'Bank Transfer Details',
    bank_account: 'Account Name: Scientific Society of Chemistry (SSC)',
    bank_name: 'Bank Name: Egyptian Arab Land Bank (EALB)',
    reg_account_number: 'Account Number:',
    reg_iban: 'IBAN:',
    reg_swift: 'SWIFT Code:',
    reg_copied: 'Copied!',
    reg_includes_title: 'Registration Includes',
    reg_include_welcome_packet: 'Conference Welcome Packet',
    reg_include_publication: 'Coverage of the publication fee for accepted papers in the conference Special Issue of Emergent Materials (Q1, Scopus), published by Springer Nature',
    reg_include_sessions: 'Access to All Sessions',
    reg_include_proceedings: 'Digital Conference Proceedings',
    reg_include_program: 'Hard copy of the program guide (For Speakers)',
    reg_include_gift_bag: 'Gift bag from the conference',
    reg_include_certificate: 'Certificate of Presentation',
    reg_include_accommodation: 'Four days / Three-night accommodation on a Soft All-Inclusive basis at the conference hotel.',
    reg_not_includes_title: 'Registration Does Not Include',
    reg_not_include_visa: 'Visa application fee',
    reg_not_include_transport: 'Airfare and transportation expenses',
    reg_not_include_one_author: 'Each registration covers one participant only.',
    reg_not_include_additional_authors: 'Co-authors wishing to attend the conference are required to register separately.',
    reg_additional_title: 'Additional Information',
    reg_additional_video: 'Video presentations are accepted for those who are unable to attend.',
    reg_additional_early: 'We strongly recommend registering during the early period.',
    reg_cancellation_title: 'Cancellation & Refund Policy',
    reg_cancellation_intro: 'Participants who wish to cancel their registration must notify the Conference Secretariat in writing via email. Refunds will be processed according to the following schedule:',
    reg_cancellation_1: 'Cancellation received on or before 31 October 2026: 80% of the registration fee will be refunded.',
    reg_cancellation_2: 'Cancellation received between 1 November and 30 November 2026: 50% of the registration fee will be refunded.',
    reg_cancellation_3: 'Cancellation received on or after 1 December 2026: No refund will be issued.',
    reg_cancellation_note: 'Please note that all approved refunds will be processed within 30 working days after the conclusion of the conference. Any bank transfer charges, currency conversion fees, or other transaction costs incurred during the payment or refund process are the responsibility of the participant.',
    reg_transfer_title: 'Registration Transfer',
    reg_transfer_desc: 'Registration may be transferred to another participant from the same institution upon written request submitted to the Conference Secretariat no later than 15 January 2027, subject to approval by the Organizing Committee.',
    venue_title: 'Venue',
    venue_location: 'Hotel on the Corniche, Sharm El-Sheikh, Egypt',
    venue_region: 'Red Sea Coast',
    venue_intro:
      'Rehana Sharm Resort provides a modern and comfortable setting for the symposium, featuring professional conference facilities, quality accommodation, and a prime location near the Red Sea. The venue offers an ideal environment for scientific exchange, networking, and international collaboration.',
    venue_accommodation_title: 'Accommodation',
    venue_accommodation_desc: 'Conference venue hotel near the beach and Sharm El-Sheikh corniche.',
    venue_tour: 'Professional Networking Experience',
    venue_tour_desc: 'A welcoming environment designed for scientific exchange, collaboration, and engagement.',
    venue_language: 'Conference Language: English',
    venue_language_desc: 'All scientific sessions, presentations, and official communications will be conducted in English.',
    organized_by: 'Organized by',
    hero_discount_text: 'Accepted papers will be published in Emergent Materials journal - Q1 (Scopus) - Springer Nature – ISSN (2522-5731) - E-ISSN (2522-574X) and will be listed as a special issue.',
    hero_discount_url: 'https://link.springer.com/journal/42247',
    footer_desc: 'Advancing Chemistry and Innovation Towards Sustainable Development',
    footer_links: 'Quick Links',
    footer_contact: 'Contact Information',
    back_to_top: 'Back to top',
    copyright: '© 2027 ACI-SD | Scientific Society of Chemistry'
  },
  ar: {
    home: 'الرئيسية',
    about: 'عن المؤتمر',
    topics: 'المحاور',
    abstract: 'الملخصات',
    registration: 'التسجيل',
    contact: 'اتصل بنا',
    venue: 'مكان الانعقاد',
    registerNow: 'سجل الآن',
    submitAbstract: 'قدم ملخص',
    hero_title: 'ACI-SD 2027',
    hero_subtitle: 'المؤتمر الدولي الأول للنهوض بالكيمياء والابتكار من أجل التنمية المستدامة',
    hero_subtitle2: 'الندوة الحادية عشرة لمجموعة البحر المتوسط لأبحاث المبيدات',
    hero_date: '27-30 يناير 2027',
    hero_location: 'شرم الشيخ، مصر',
    about_title: 'عن المؤتمر',
    about_invite_title: 'الدعوة',
    about_invite:
      'زملائي الأعزاء، الباحثون، الأكاديميون، خبراء الصناعة، والطلاب،\n\nيسعدنا الإعلان عن انعقاد المؤتمر الدولي الأول للنهوض بالكيمياء والابتكار نحو المستقبل: تكنولوجيا النانو والذكاء الاصطناعي وريادة الأعمال من أجل التنمية المستدامة (ACI-SD 2027)، والذي يُعقد بالتزامن مع الندوة الحادية عشرة لمجموعة البحر المتوسط لأبحاث المبيدات، في شرم الشيخ، مصر، خلال الفترة من 27 إلى 30 يناير 2027. ينظم المؤتمر الجمعية العلمية للكيمياء (SSC) وجامعة برج العرب التكنولوجية بالتعاون مع مؤسسات أكاديمية وبحثية دولية ومحلية مرموقة، ليجمع العلماء والباحثين والمبتكرين وقادة الصناعة وصناع السياسات والطلاب من جميع أنحاء العالم. يهدف ACI-SD 2027 إلى توفير منصة دولية ديناميكية لتبادل المعرفة العلمية وعرض الأبحاث المتطورة وتعزيز التعاون متعدد التخصصات في مجالات الكيمياء وتكنولوجيا النانو والذكاء الاصطناعي والصناعة المستدامة والتقنيات البيئية والطاقة والزراعة وريادة الأعمال والابتكار. يسعى المؤتمر إلى تعزيز الصلة بين البحث العلمي والتطبيقات الصناعية وأهداف التنمية المستدامة من خلال الحوار البناء وتبادل المعرفة. سيتضمن البرنامج العلمي محاضرات رئيسية وندوات مدعوة وعروضًا شفوية وملصقات وجلسات نقاشية ومعارض صناعية وفرص للتواصل تهدف إلى تشجيع التعاون بين الأوساط الأكاديمية والصناعية والحكومية. وسيتم التركيز بشكل خاص على التقنيات الناشئة والمواد المتقدمة والتصنيع الذكي والابتكار القائم على الذكاء الاصطناعي والزراعة المستدامة وحماية البيئة وتقنيات المياه والطاقة المتجددة ونقل التكنولوجيا.\n\nبالتوازي، ستواصل الندوة الحادية عشرة لمجموعة البحر المتوسط لأبحاث المبيدات تقليدها العريق في تعزيز التميز العلمي والتعاون الدولي في أبحاث المبيدات والسلامة البيئية وحماية النباتات والزراعة المستدامة والمجالات ذات الصلة. ستجمع الندوة نخبة من الخبراء والباحثين الشباب لمناقشة أحدث التطورات والتحديات والآفاق المستقبلية في هذه المجالات المهمة. يوفر مكان انعقاد المؤتمر في مدينة شرم الشيخ الجميلة بيئة ملهمة للتبادل العلمي والتواصل الدولي. ستتاح للمشاركين فرصة التفاعل مع خبراء مرموقين وبناء تعاونات جديدة والمساهمة في صياغة حلول مبتكرة للتحديات العلمية والمجتمعية العالمية. ندعو الباحثين والأكاديميين والمهنيين والشركاء الصناعيين وطلاب الدراسات العليا وممثلي المنظمات الحكومية وغير الحكومية للمشاركة في هذا الحدث الدولي المتميز والمساهمة في نجاحه العلمي. نتطلع إلى الترحيب بكم في شرم الشيخ، مصر، في تجمع ملهم ومثمر للمجتمع العلمي الدولي.',
    about_host_title: 'الجهة المنظمة',
    about_ssc:
      'الجمعية العلمية للكيمياء (SSC) هي منظمة علمية مستقلة تهدف إلى النهوض بالعلوم الكيميائية وتعزيز التميز البحثي ودعم الابتكار من أجل التنمية المستدامة. تعمل الجمعية كمنصة متعددة التخصصات تجمع الباحثين والأكاديميين وخبراء الصناعة وصناع السياسات والعلماء الشباب لتسهيل التعاون العلمي وتبادل المعرفة وبناء القدرات على المستويين الوطني والدولي. تلتزم SSC بدعم البحث العلمي والابتكار وريادة الأعمال ونقل التكنولوجيا من خلال تنظيم المؤتمرات الدولية وورش العمل العلمية والبرامج التدريبية والمبادرات البحثية التعاونية. تعزز الجمعية بنشاط المناهج متعددة التخصصات التي تدمج الكيمياء مع المجالات الناشئة مثل تكنولوجيا النانو والذكاء الاصطناعي والمواد المتقدمة والتقنيات البيئية والتكنولوجيا الحيوية والتنمية الصناعية المستدامة. من خلال شبكتها الواسعة من المؤسسات الأكاديمية ومراكز البحوث والشركاء الصناعيين والخبراء الدوليين، تساهم SSC في تعزيز التعاون العلمي وتقديم حلول مؤثرة للتحديات العالمية المتعلقة بالصحة والطاقة والمياه والبيئة والزراعة والتقنيات المستدامة. تكرس الجمعية جهودها لتمكين الجيل القادم من العلماء والمبتكرين مع دعم ترجمة الاكتشافات العلمية إلى تطبيقات عملية تفيد المجتمع والصناعة. بصفتها منظمة المؤتمر الدولي للنهوض بالكيمياء والتكنولوجيا التطبيقية والابتكار نحو المستقبل (ACI-SD 2027)، تؤكد SSC التزامها بتعزيز التميز العلمي والتعاون الدولي والتنمية المستدامة القائمة على الابتكار.',
    about_batu:
      'جامعة برج العرب التكنولوجية (BATU) هي إحدى الجامعات التكنولوجية الرائدة في مصر، أُنشئت للنهوض بالتعليم التطبيقي والابتكار والبحث الموجه نحو الصناعة بما يتماشى مع رؤية مصر 2030 وأهداف التنمية المستدامة. تقع الجامعة في موقع استراتيجي بمدينة برج العرب—إحدى أكبر المناطق الصناعية والاقتصادية في مصر والشرق الأوسط—لتكون مركزًا ديناميكيًا يربط الأوساط الأكاديمية والبحث والتكنولوجيا والصناعة. تلتزم BATU بتطوير خريجين ذوي مهارات عالية وتعزيز التميز العلمي من خلال التعليم متعدد التخصصات والبحث التطبيقي والابتكار التكنولوجي وريادة الأعمال والتنمية الصناعية المستدامة. تعزز الجامعة شراكات قوية مع القطاعات الصناعية والمؤسسات البحثية والمنظمات الدولية لتسريع نقل المعرفة ودعم الانتقال نحو اقتصاد قائم على المعرفة والابتكار. من خلال التزامها بالجودة الأكاديمية والتقدم التكنولوجي والتعاون الدولي، تلعب BATU دورًا نشطًا في مواجهة التحديات المعاصرة في العلوم والتكنولوجيا والاستدامة والتحول الصناعي، مع المساهمة في مبادرات التنمية الإقليمية والعالمية.',
    about_theme_title: 'محور المؤتمر',
    about_theme:
      'تشرفت اللجنة المنظمة للمؤتمر الدولي للنهوض بالكيمياء والتكنولوجيا التطبيقية والابتكار نحو المستقبل: تكنولوجيا النانو والذكاء الاصطناعي وريادة الأعمال والصناعة المستدامة (ACI-SD 2027)، والذي يُعقد بالتزامن مع الندوة الحادية عشرة لمجموعة البحر المتوسط لأبحاث المبيدات، بدعوة الباحثين والأكاديميين وقادة الصناعة والمبتكرين ورواد الأعمال والطلاب من جميع أنحاء العالم للمشاركة في هذا الحدث الدولي المتميز، والذي سيقام في شرم الشيخ، مصر، خلال الفترة من 27 إلى 30 يناير 2027. يهدف ACI-SD 2027 إلى معالجة التحديات العلمية والتكنولوجية الأكثر إلحاحًا والناشئة التي تشكل مستقبل التنمية المستدامة. سيوفر المؤتمر منصة متعددة التخصصات لعرض الأبحاث المتطورة وتبادل الأفكار المبتكرة وتعزيز التعاون بين الأوساط الأكاديمية والصناعية والمؤسسات البحثية وصناع السياسات. يعكس محور المؤتمر "النهوض بالكيمياء والتكنولوجيا التطبيقية والذكاء الاصطناعي والابتكار من أجل مستقبل مستدام" الحاجة المتزايدة لدمج الاكتشاف العلمي والتقدم التكنولوجي وريادة الأعمال والابتكار الصناعي لمواجهة التحديات العالمية المتعلقة بالطاقة والبيئة والمياه والزراعة والصحة والنمو الاقتصادي المستدام. من خلال المحاضرات الرئيسية والعروض العلمية وحلقات النقاش وفرص التواصل، يسعى المؤتمر إلى تعزيز التعاون الدولي وتسريع ترجمة المعرفة العلمية إلى حلول عملية.',
    about_obj_title: 'الأهداف',
    about_obj_lead: 'بعد المشاركة في هذا المؤتمر، يجب أن يكون المشاركون قادرين على:',
    about_objective_1:
      'مناقشة الاتجاهات الحالية والناشئة في الكيمياء وتكنولوجيا النانو والذكاء الاصطناعي والصناعة المستدامة والتقنيات البيئية.',
    about_objective_2:
      'تحديد التحديات والفرص البحثية الرئيسية في المواد المتقدمة والطاقة والمياه والزراعة والابتكار الصناعي.',
    about_objective_3:
      'تبادل المعرفة العلمية وأفضل الممارسات بين الباحثين والمهنيين الصناعيين ورواد الأعمال وصناع السياسات.',
    about_objective_4:
      'استكشاف دور الذكاء الاصطناعي والتحول الرقمي في تسريع الاكتشاف العلمي والتنمية الصناعية.',
    about_objective_5:
      'تعزيز التعاون متعدد التخصصات والشراكات الدولية لمواجهة تحديات الاستدامة العالمية.',
    about_objective_6:
      'تسليط الضوء على التطورات الحديثة في أبحاث المبيدات والزراعة المستدامة والسلامة البيئية والابتكار الكيميائي الزراعي.',
    about_objective_7:
      'تعزيز نقل التكنولوجيا وريادة الأعمال والحلول القائمة على الابتكار التي تدعم التنمية الاقتصادية والمجتمعية المستدامة.',
    about_objective_8:
      'تشجيع الباحثين الشباب والطلاب على الانخراط في البحث العلمي والابتكار والتعاون الدولي.',
    stat_international: 'مؤتمر دولي',
    stat_topics: '8 محاور بحثية',
    stat_speakers: '+50 متحدث',
    stat_location: 'شرم الشيخ، مصر',
    topics_title: 'محاور المؤتمر',
    topic_chemistry: 'الكيمياء المتقدمة والمواد الوظيفية للتطبيقات الصناعية',
    topic_chemistry_desc: 'أبحاث متطورة في التركيب الكيميائي والبوليمرات الذكية والأطر الفلزية العضوية والمواد المتقدمة للتطبيقات الصناعية',
    topic_nano: 'تكنولوجيا النانو وعلوم المقياس النانوي',
    topic_nano_desc: 'ابتكارات في علوم النانو والأجهزة المعززة بالنانو وتطبيقاته الصناعية',
    topic_energy: 'الطاقة والاستدامة والتقنيات النظيفة',
    topic_energy_desc: 'أنظمة الطاقة المتجددة وحلول التخزين وتقنيات الهيدروجين وممارسات الطاقة المستدامة',
    topic_agro: 'علوم الكيمياء الزراعية والزراعة الذكية والسلامة البيئية',
    topic_agro_desc: 'الزراعة المستدامة والزراعة الذكية وأبحاث المبيدات والسلامة البيئية والتكنولوجيا الحيوية الزراعية',
    topic_ai: 'الذكاء الاصطناعي وعلوم البيانات والأنظمة الكيميائية الذكية',
    topic_ai_desc: 'التعلم الآلي وتحليل البيانات والاكتشاف المدعوم بالذكاء الاصطناعي وأنظمة التصنيع الكيميائي الذكية',
    topic_enviro: 'التقنيات البيئية والمياه والاقتصاد الدائري',
    topic_enviro_desc: 'التقنيات النظيفة لمعالجة المياه ومكافحة التلوث واسترداد الموارد والاقتصاد الدائري',
    topic_engineering: 'الهندسة الكيميائية وهندسة العمليات من أجل الصناعة المستدامة',
    topic_engineering_desc: 'تصميم العمليات المتقدمة وتكثيفها وتقنيات الفصل والهندسة الصناعية المستدامة',
    topic_innovation: 'الابتكار وريادة الأعمال ونقل التكنولوجيا',
    topic_innovation_desc: 'تحويل البحث إلى تطبيقات تجارية والشركات الناشئة والشراكات بين الصناعة والأوساط الأكاديمية',
    committee: 'اللجان',
    committee_title: 'لجان المؤتمر',
    executiveCommitteeNav: 'اللجنة التنفيذية',
    organizingCommitteeNav: 'اللجنة التنظيمية',
    scientificCommitteeNav: 'اللجنة العلمية',
    abstract_title: 'الدعوة لتقديم الملخصات',
    abstract_email: 'أرسل إلى: sci.s.o.chemistry@gmail.com',
    abstract_words: '200-300 كلمة',
    abstract_format: '12-pt حجم الخط, Times New Roman، عريض، A4',
    abstract_deadline: 'الموعد النهائي: 30 نوفمبر 2026',
    abstract_oral: 'قالب العرض الشفهي',
    abstract_oral_subtitle: 'مدة التقديم: 15\u201320 دقيقة',
    abstract_poster: 'قالب عرض الملصق',
    abstract_poster_subtitle: 'حجم الملصق: 90 \u00d7 120 سم',
    abstract_template: 'قالب الملخص',
    abstract_template_subtitle: 'تحميل قالب الملخص الرسمي للمؤتمر.',
    downloadTemplate: 'تحميل قالب الملخص',
    dates_title: 'التواريخ المهمة',
    date_submission: 'تقديم الملخص',
    date_acceptance: 'الإخطار بالقبول',
    date_final_paper: 'تقديم الورقة النهائية',
    date_registration: 'الموعد النهائي للتسجيل',
    registration_title: 'التسجيل',
    reg_intro: 'مرحبًا بكم في المؤتمر. يرجى الاطلاع أدناه على رسوم التسجيل والمعلومات ذات الصلة.',
    reg_fee_schedule: 'جدول رسوم التسجيل',
    reg_header_category: 'الفئة',
    reg_header_double: 'غرفة مزدوجة',
    reg_header_single: 'غرفة مفردة',
    reg_header_egp_onsite: 'مصري (جنيه) حضور شخصي',
    reg_header_egp_online: 'مصري (جنيه) عبر الإنترنت',
    reg_header_usd_onsite: 'دولي (دولار) حضور شخصي',
    reg_header_usd_online: 'دولي (دولار) عبر الإنترنت',
    reg_category_full_paper: 'تقديم ورقة كاملة',
    reg_category_abstract: 'تقديم ملخص فقط',
    reg_category_attendee: 'حضور (غير مقدم)',
    reg_category_accompanying: 'مرافق',
    reg_not_available: '\u2014',
    reg_student_title: 'خصم الطلاب',
    reg_student_text: 'يحصل طلاب البكالوريوس والدراسات العليا المتفرغون على خصم 15% على رسوم التسجيل المستحقة عند تقديم بطاقة هوية طلابية سارية المفعول.',
    bank_details: 'تفاصيل التحويل البنكي',
    bank_account: 'الحساب: الجمعية العلمية للكيمياء',
    bank_name: 'البنك: بنك الأراضي المصري العربي',
    reg_account_number: 'رقم الحساب:',
    reg_iban: 'IBAN:',
    reg_swift: 'SWIFT Code:',
    reg_copied: 'تم النسخ!',
    reg_includes_title: 'يشمل التسجيل',
    reg_include_welcome_packet: 'حقيبة ترحيبية للمؤتمر',
    reg_include_publication: 'تغطية رسوم النشر للأوراق المقبولة في العدد الخاص بالمؤتمر من مجلة Emergent Materials (Q1, Scopus) المنشورة من قبل Springer Nature',
    reg_include_sessions: 'الوصول لجميع الجلسات',
    reg_include_proceedings: 'وقائع المؤتمر الرقمية',
    reg_include_program: 'نسخة مطبوعة من دليل البرنامج (للمتحدثين)',
    reg_include_gift_bag: 'حقيبة هدايا من المؤتمر',
    reg_include_certificate: 'شهادة تقديم',
    reg_include_accommodation: 'إقامة لمدة أربعة أيام / ثلاث ليالٍ بنظام الإقامة الشاملة المخففة في فندق المؤتمر.',
    reg_not_includes_title: 'لا يشمل التسجيل',
    reg_not_include_visa: 'رسوم طلب التأشيرة',
    reg_not_include_transport: 'تذاكر الطيران ومصاريف النقل',
    reg_not_include_one_author: 'يغطي التسجيل مشاركًا واحدًا فقط.',
    reg_not_include_additional_authors: 'يجب على المؤلفين المشاركين الراغبين في حضور المؤتمر التسجيل بشكل منفصل.',
    reg_additional_title: 'معلومات إضافية',
    reg_additional_video: 'يتم قبول العروض التقديمية بالفيديو لمن لا يستطيعون الحضور شخصيًا.',
    reg_additional_early: 'نوصي بشدة بالتسجيل المبكر.',
    reg_cancellation_title: 'سياسة الإلغاء واسترداد الرسوم',
    reg_cancellation_intro: 'يجب على المشاركين الراغبين في إلغاء تسجيلهم إخطار أمانة المؤتمر كتابيًا عبر البريد الإلكتروني. سيتم معالجة المبالغ المستردة وفقًا للجدول التالي:',
    reg_cancellation_1: 'الإلغاء في أو قبل 31 أكتوبر 2026: سيتم استرداد 80% من رسوم التسجيل.',
    reg_cancellation_2: 'الإلغاء بين 1 نوفمبر و30 نوفمبر 2026: سيتم استرداد 50% من رسوم التسجيل.',
    reg_cancellation_3: 'الإلغاء في أو بعد 1 ديسمبر 2026: لن يتم إصدار أي استرداد.',
    reg_cancellation_note: 'يرجى العلم أن جميع المبالغ المستردة المعتمدة ستتم معالجتها في غضون 30 يوم عمل بعد انتهاء المؤتمر. أي رسوم تحويل بنكي أو رسوم تحويل عملات أو تكاليف معاملات أخرى تتكبدها أثناء عملية الدفع أو الاسترداد هي مسؤولية المشارك.',
    reg_transfer_title: 'تحويل التسجيل',
    reg_transfer_desc: 'يجوز تحويل التسجيل إلى مشارك آخر من نفس المؤسسة بناءً على طلب كتابي يُقدم إلى أمانة المؤتمر في موعد أقصاه 15 يناير 2027، وذلك بعد موافقة اللجنة المنظمة.',
    venue_title: 'مكان الانعقاد',
    venue_location: 'فندق على الكورنيش، شرم الشيخ، مصر',
    venue_region: 'ساحل البحر الأحمر',
    venue_intro:
      'يوفر منتجع ريهانا شرم الشيخ بيئة حديثة ومريحة للندوة، مع مرافق مؤتمرات احترافية وإقامة عالية الجودة وموقع متميز بالقرب من البحر الأحمر. يقدم المكان بيئة مثالية للتبادل العلمي والتواصل والتعاون الدولي.',
    venue_accommodation_title: 'الإقامة',
    venue_accommodation_desc: 'فندق انعقاد المؤتمر بالقرب من الشاطئ وكورنيش شرم الشيخ.',
    venue_tour: 'بيئة مهنية للتواصل',
    venue_tour_desc: 'أجواء مثالية للتبادل العلمي وبناء الشراكات وتعزيز التفاعل بين المشاركين.',
    venue_language: 'لغة المؤتمر: الإنجليزية',
    venue_language_desc: 'ستُعقد جميع الجلسات العلمية والعروض التقديمية والمراسلات الرسمية باللغة الإنجليزية.',
    organized_by: 'تنظيم',
    hero_discount_text: 'سيتم نشر الأوراق المقبولة في مجلة Emergent Materials - Q1 (Scopus) - Springer Nature – ISSN (2522-5731) - E-ISSN (2522-574X) وستُدرج كعدد خاص.',
    hero_discount_url: 'https://link.springer.com/journal/42247',
    footer_desc: 'النهوض بالكيمياء والابتكار نحو التنمية المستدامة',
    footer_links: 'روابط سريعة',
    footer_contact: 'معلومات الاتصال',
    back_to_top: 'العودة إلى الأعلى',
    copyright: '© 2027 ACI-SD | الجمعية العلمية للكيمياء'
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      <div dir={language === 'ar' ? 'rtl' : 'ltr'} className={language === 'ar' ? 'font-cairo' : 'font-inter'}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
